// Generated by CoffeeScript 1.10.0
(function() {
  var getUserLocale;

  if (typeof variable !== "undefined" && variable !== null) {
    console.log('variable is both declared and initialized with a non-null value');
  }

  getUserLocale = function() {
    return this.locale != null ? this.locale : this.locale = DB.getLocaleByUser(User.current);
  };

}).call(this);

//# sourceMappingURL=coffeescript-diddies.js.map
