// Generated by CoffeeScript 1.10.0
(function() {
  var myTwitter, mytwitter;

  myTwitter = require('./twitterAPI');

  mytwitter = new myTwitter();

  console.log(mytwitter.getTimeline());

  mytwitter.startStream();

}).call(this);

//# sourceMappingURL=startTweets.js.map
