// Generated by CoffeeScript 1.10.0
(function() {
  var getHomeTimeline, params, startStream, twitter, twitterAPI;

  twitterAPI = require('node-twitter-api');

  twitter = require('twitter');

  console.log('whatup');

  params = {
    screen_name: 'msgiannamarie'
  };

  getHomeTimeline = function() {
    return client.get('statuses/home_timeline', params, function(error, tweets, response) {
      if (!error) {
        return tweets;
      }
    });
  };

  startStream = function() {
    var access_token, access_token_secret, client, consumer_key, consumer_secret, home_timeline;
    client.stream('user', {
      "with": 'followings',
      delimited: 'true',
      language: 'en'
    }, function(stream) {
      stream.on('data', function(tweet) {
        return console.log(tweet.text);
      });
      return stream.on('error', function(error) {
        throw error;
      });
    });
    consumer_key = this.process.env['TWITTER_CONSUMER_KEY'];
    consumer_secret = this.process.env['TWITTER_CONSUMER_SECRET'];
    access_token = this.process.env['TWITTER_ACCESS_TOKEN'];
    access_token_secret = this.process.env['TWITTER_ACCESS_SECRET'];
    client = new twitter({
      consumer_key: consumer_key,
      consumer_secret: consumer_secret,
      access_token_key: access_token,
      access_token_secret: access_token_secret
    });
    console.log('here');
    home_timeline = getHomeTimeline();
    return console.log(home_timeline);
  };

}).call(this);

//# sourceMappingURL=twitApi.js.map
